version: '3.1'

services:

  db:
    image: mysql:8.2.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: ilima
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - business

  ms-pagamento:
    image: ilimafilho/pagamento:latest
    container_name: ms-pagamento
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 8100:8100
    networks:
      - business
    depends_on:
      - db

networks:
  business:
    internal:
      false