# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.2.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: ilima
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - business

networks:
  business:
    internal:
      false